cc_test(
    name = "Test1",
    srcs = ["Test.cpp" ],
    deps = ["@googletest//:gtest_main",
    "//:Calcy",
    "//lib/addition:add",
    "//lib/Division:Divi",
    "//lib/Multipication:Multi",
    "//lib/Subraction:Sub",
    ],

)